version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: default
    main: ./cmd/kubectx
    binary: kubectx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: philipparndt
    name: kubectx

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: kubectx

    goarm: 6
    goamd64: v1

    install: |
      bin.install "kubectx"

    url_template: "https://github.com/philipparndt/kubectx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: Philipp Arndt
      email: opensource@rnd7.de

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    directory: Formula

    caveats: |
      Run using kubectx. Bash, Zsh, Fish, and PowerShell completions are installed automatically.

    homepage: "https://github.com/philipparndt/kubectx"

    description: "Command-line tool for managing Kubernetes contexts"

    license: "Apache-2.0"

    post_install: |
      begin
        bash_output = Utils.safe_popen_read("#{bin}/kubectx", "completion", "bash")
        (bash_completion/"kubectx").write bash_output
      rescue => e
        opoo "Failed to install bash completion: #{e}"
      end

      begin
        zsh_output = Utils.safe_popen_read("#{bin}/kubectx", "completion", "zsh")
        (zsh_completion/"_kubectx").write zsh_output
      rescue => e
        opoo "Failed to install zsh completion: #{e}"
      end

      begin
        fish_output = Utils.safe_popen_read("#{bin}/kubectx", "completion", "fish")
        (fish_completion/"kubectx.fish").write fish_output
      rescue => e
        opoo "Failed to install fish completion: #{e}"
      end

    repository:
      owner: philipparndt
      name: homebrew-kubectx
      branch: main

      pull_request:
        enabled: false
        draft: false
